# Generated by Django 4.1.2 on 2022-10-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_product_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='body',
        ),
    ]
