# Generated by Django 4.1.2 on 2022-10-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_remove_product_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
