# Generated by Django 4.1.2 on 2022-10-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_product_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(default='', max_length=255),
        ),
    ]
