# Generated by Django 4.1.2 on 2022-11-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Shooter', 'Shooter'), ('Horror', 'Horror'), ('RPG', 'RPG'), ('Adventure', 'Adventure'), ('SoulsLike', 'SoulsLike')], default=None, max_length=50),
        ),
    ]
