# Generated by Django 4.1.2 on 2022-12-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_alter_product_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Technical_desc',
            field=models.TextField(default=''),
        ),
    ]
