# Generated by Django 4.1.2 on 2022-12-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_product_technical_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default='true'),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Shooter', 'Shooter'), ('Horror', 'Horror'), ('Adventure', 'Adventure'), ('RPG', 'RPG'), ('SoulsLike', 'SoulsLike')], default='RPG', max_length=20),
        ),
    ]
