# Generated by Django 4.1.2 on 2022-12-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('SoulsLike', 'SoulsLike'), ('RPG', 'RPG'), ('Horror', 'Horror'), ('Shooter', 'Shooter')], default='RPG', max_length=20),
        ),
    ]
