# Generated by Django 4.1.2 on 2022-12-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_alter_product_group_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('SoulsLike', 'SoulsLike'), ('Adventure', 'Adventure'), ('Shooter', 'Shooter'), ('Horror', 'Horror'), ('RPG', 'RPG')], default='RPG', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
