# Generated by Django 4.1.2 on 2022-12-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_alter_product_group_alter_product_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Horror', 'Horror'), ('SoulsLike', 'SoulsLike'), ('Adventure', 'Adventure'), ('RPG', 'RPG'), ('Shooter', 'Shooter')], default='RPG', max_length=20),
        ),
    ]
