# Generated by Django 4.1.2 on 2022-12-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0022_alter_product_unique_together_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('SoulsLike', 'SoulsLike'), ('Shooter', 'Shooter'), ('RPG', 'RPG'), ('Horror', 'Horror')], default='RPG', max_length=20),
        ),
    ]
