# Generated by Django 4.1.2 on 2022-12-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0023_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('SoulsLike', 'SoulsLike'), ('Adventure', 'Adventure'), ('RPG', 'RPG'), ('Shooter', 'Shooter'), ('Horror', 'Horror')], default='RPG', max_length=20),
        ),
    ]
