# Generated by Django 4.1.2 on 2022-12-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0028_alter_product_group_purchased_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('SoulsLike', 'SoulsLike'), ('Adventure', 'Adventure'), ('Horror', 'Horror'), ('RPG', 'RPG'), ('Shooter', 'Shooter')], default='RPG', max_length=20),
        ),
    ]
