# Generated by Django 4.1.2 on 2022-12-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0031_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Horror', 'Horror'), ('Shooter', 'Shooter'), ('SoulsLike', 'SoulsLike'), ('RPG', 'RPG'), ('Roguelike', 'Roguelike')], default='RPG', max_length=20),
        ),
    ]
