# Generated by Django 4.1.2 on 2022-12-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0032_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Roguelike', 'Roguelike'), ('SoulsLike', 'SoulsLike'), ('RPG', 'RPG'), ('Shooter', 'Shooter'), ('Adventure', 'Adventure')], default='RPG', max_length=20),
        ),
    ]
