# Generated by Django 4.1.2 on 2022-12-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0034_remove_purchased_products_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Horror', 'Horror'), ('SoulsLike', 'SoulsLike'), ('Adventure', 'Adventure'), ('Roguelike', 'Roguelike'), ('RPG', 'RPG'), ('Shooter', 'Shooter')], default='RPG', max_length=20),
        ),
    ]
