# Generated by Django 4.1.2 on 2022-12-14 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0035_alter_product_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased_products',
            name='product_id',
        ),
        migrations.AddField(
            model_name='purchased_products',
            name='key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchased_products',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Shooter', 'Shooter'), ('Horror', 'Horror'), ('SoulsLike', 'SoulsLike'), ('RPG', 'RPG'), ('Roguelike', 'Roguelike')], default='RPG', max_length=20),
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='page.product')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
