# Generated by Django 4.1.2 on 2022-12-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0037_remove_purchased_products_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Shooter', 'Shooter'), ('Roguelike', 'Roguelike'), ('Adventure', 'Adventure'), ('RPG', 'RPG'), ('Horror', 'Horror'), ('SoulsLike', 'SoulsLike')], default='RPG', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchased_products',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.product'),
        ),
    ]
