# Generated by Django 4.1.2 on 2022-12-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0039_alter_product_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased_products',
            name='product_id',
        ),
        migrations.AddField(
            model_name='purchased_products',
            name='key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchased_products',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Shooter', 'Shooter'), ('Horror', 'Horror'), ('SoulsLike', 'SoulsLike'), ('Roguelike', 'Roguelike'), ('RPG', 'RPG')], default='RPG', max_length=20),
        ),
    ]
